language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5
    - php: 7
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - phpenv rehash
  - git clone -b prefer-source git://github.com/kinglozzer/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --prefer-source
  - cd ~/builds/ss

script:
  - phpunit oauth-login/tests/
