---
Name: oauthcontroller
---
Bigfork\SilverStripeOAuth\Client\Control\Controller:
  token_handlers:
    loginhandler:
      priority: 1
      context: login
      class: Bigfork\SilverStripeOAuth\Client\Handler\LoginTokenHandler
SilverStripe\Security\Member:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\MemberExtension
